/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/shirt_baked.gltf 
*/

import React from 'react'
import * as THREE from 'three'
import { AccumulativeShadows, Decal, useGLTF, useTexture } from '@react-three/drei'
import { useSnapshot } from 'valtio'
import { state } from '../store'
import { useThree } from '@react-three/fiber'


export function Shirt(props) {
  const { gl } = useThree(); // Access the WebGL context

  const snap=useSnapshot(state)

  const texture=useTexture(`./images/${snap.selectedDecal}.png`)

  if (texture) {
    texture.anisotropy = gl.capabilities.getMaxAnisotropy();
   }

  const { nodes, materials } = useGLTF('./models/shirt_baked.glb')

  materials.lambert1.color=new THREE.Color(snap.selectedColor)


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.T_Shirt_male.geometry} material={materials.lambert1} >
      <Decal map={texture}
       position={[0.01,0,0.15]}
       rotation={[0,0,0]}
       scale={0.15}
       opacity={0.7}

       
       
        
      />
      </mesh>
    </group>
  )
}




useGLTF.preload('./models/shirt_baked.glb')



